### ISSUE TITLE
NullReferenceException WebXRController.cs

### ISSUE THREAD

**Issue by ws18** [MozillaReality/unity-webxr-export#414]
If in any of my Input Map I set GamepadIsButton = false for Inputs other than the default inputs specified in the sample project, I always get a NullReferenceException on WebXRController at line 80. Particularly, I'm trying to set Gamepad ID 3 to be an axis (should be Thumbstick Y) instead of a button. But if I do, I get the error and everything stops working.

Is it a bug or am I doing something horribly wrong?

**Comment by msub2** [comment]
Encountering the same issue right now. Did you ever find a fix?

EDIT: After digging around I think it's because it's checking for XRDevice.isPresent, which will return false even if you have a device present. I'm working on a fork that updates some things and switches it to check for XRDisplaySystem.running instead
